Launch

diff --git a/.github/workflows/release-from-changelog.yml b/.github/workflows/release-from-changelog.yml
--- a/.github/workflows/release-from-changelog.yml
+++ b/.github/workflows/release-from-changelog.yml
@@ -42,9 +42,12 @@ jobs:
       - name: Create new GitHub release if version is new
         if: env.version != env.latest_release && env.version != '' && env.latest_release != 'Unreleased'
         run: |
-          echo "Would be creating release $version"
-          echo "Would be using the following changelog:"
-          cat RELEASE_NOTES.md
-          # gh release create "$version" --title "$version" --notes-file RELEASE_NOTES.md
+          # Check if $version is a semver version (vX.Y.Z)
+          if [[ ! "$version" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Invalid version: $version"
+            exit 1
+          fi
+
+          gh release create "$version" --title "$version" --notes-file RELEASE_NOTES.md
         env:
           GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
