Adjust release-from-changelog

diff --git a/.github/workflows/release-from-changelog.yml b/.github/workflows/release-from-changelog.yml
--- a/.github/workflows/release-from-changelog.yml
+++ b/.github/workflows/release-from-changelog.yml
@@ -39,21 +39,22 @@ jobs:
         id: extract_notes
         run: |
           sed -n '/^## '"$version"'/,/^## /p' CHANGELOG.md | sed '1d;$d' > RELEASE_NOTES.md
+          sed -i ':a;N;$!ba;s/\n  / /g' RELEASE_NOTES.md
           echo "Release notes:"
           cat RELEASE_NOTES.md
         shell: bash
 
-      - name: Create new GitHub release if version is new
-        if: env.version != env.latest_release && env.version != '' && env.latest_release != 'Unreleased'
-        env:
-          GH_TOKEN: ${{ github.token }}
-        run: |
-          # Check if $version is a semver version (vX.Y.Z)
-          if [[ ! "$version" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-            echo "Invalid version: $version"
-            exit 1
-          fi
-          gh release create "$version" \
-            --title "$version" \
-            --notes-file RELEASE_NOTES.md \
-            -d --fail-on-no-commits
+      # - name: Create new GitHub release if version is new
+      #   if: env.version != env.latest_release && env.version != '' && env.latest_release != 'Unreleased'
+      #   env:
+      #     GH_TOKEN: ${{ github.token }}
+      #   run: |
+      #     # Check if $version is a semver version (vX.Y.Z)
+      #     if [[ ! "$version" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+      #       echo "Invalid version: $version"
+      #       exit 1
+      #     fi
+      #     gh release create "$version" \
+      #       --title "$version" \
+      #       --notes-file RELEASE_NOTES.md \
+      #       -d --fail-on-no-commits
